2019년 티저 홈페이지 추가
openstack-kr/event.openstack.or.kr pull request #4
Opened 2019-03-21 14:48 UTC by ppiyakk2

2019-03-21 14:55 UTC, bluejayA requested changes

2019-03-21 14:55 UTC, bluejayKR commented on 2019/index.html
> +                <li><a href="#" class="active_btn">스피커 신청</a></li>
링크 넣어주세요 https://goo.gl/62sYoA

2019-03-21 14:55 UTC, bluejayKR commented on 2019/index_en.html
> +<title>Open Infra Days Korea 2018: Countdown!</title>
Title 2019년에 맞게 바꿔주세요

2019-03-21 14:55 UTC, bluejayKR commented on 2019/index.html
> +<title>Open Infra Days Korea 2018: Countdown!</title>
2019년에 맞게 변경 필요

2019-03-21 14:55 UTC, bluejayKR commented on 2019/index_en.html
> +            <p class="sub_txt"><b>June 28-29, 2018. Coex.</b> | Pre-registration homepage will open on <b>TBD</b><br /><br />
2019년에 맞게 변경 필요

2019-03-21 15:05 UTC, ianychoi requested changes

2019-03-21 15:05 UTC, ianychoi commented on 2019/index.html
> +<title>Open Infra Days Korea 2018: Countdown!</title>
Open Infrastructure Days & Cloud Native Days Korea 2019: Countdown!

2019-03-21 15:05 UTC, ianychoi commented on 2019/index.html
> +            <a href="https://groups.openstack.org/groups/korea">OpenStack 한국 커뮤니티</a>, <a href="https://www.meetup.com/Cloud-Native-Computing-Seoul/">Kubernetes 커뮤니티</a>, <a href="https://ceph.com/co
"오픈소스기반의" -> "오픈소스 기반의"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index.html
> +                <li><a href="#" class="active_btn">스피커 신청</a></li>
"스피커 신청" -> "발표 신청"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index.html
> +                <li><a href="mailto:master@openinfradays.kr">스폰서/행사 문의</a></li>
-> "후원/행사 문의"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index.html
> +                <li><a href="http://event.openstack.or.kr/2018">지난 행사 보기</a></li>
->"https://event.openinfradays.kr/2018"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index_en.html
> +<title>Open Infra Days Korea 2018: Countdown!</title>
-> "Open Infrastructure Days & Cloud Native Days Korea 2019: Countdown!"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index_en.html
> +            <p class="sub_txt"><b>June 28-29, 2018. Coex.</b> | Pre-registration homepage will open on <b>TBD</b><br /><br />
-> "July 18-19, 2019, Buildings around Eulji-ro"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index_en.html
> +            <p class="main_txt">Open Infra Days Korea 2018</p>
-> "Open Infrastructure Days & Cloud Native Days Korea 2019"

2019-03-21 15:05 UTC, ianychoi commented on 2019/index_en.html
> +                <li><a href="http://event.openstack.or.kr/2017">Last Event<img src="img/arrow.png" alt=""></a></li>
->"https://event.openinfradays.kr/2018"

2019-03-23 00:27 UTC, bluejayA approved these changes

2019-03-23 01:05 UTC, merged